config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'estimates#index'
  resources :estimates do
    patch 'validate', to: 'estimates#validate', on: :member

    resources :items
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/estimate.rb
# frozen_string_literal: true

class Estimate < ApplicationRecord
  has_many :items, dependent: :delete_all

  accepts_nested_attributes_for :items, allow_destroy: true, reject_if: :all_blank

  def total_base_amount
    items.sum(&:total_price)
  end

  def total_vat_amount
    items.sum(&:vat_rate)
  end

  def total_with_tax
    items.sum(&:total_price_with_vat)
  end
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  ALLOWED_VAT_RATES = %w[5.5 10 20].freeze

  belongs_to :estimate

  validates :vat_rate,
            presence: true,
            inclusion: { in: ALLOWED_VAT_RATES.map(&:to_d) }

  validates :name, :unit_price, presence: true

  def total_price_with_vat
    total_price + (total_price * (vat_rate / 100))
  end

  def total_price
    unit_price * quantity
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  add_flash_types :success, :warning, :danger, :info

  def check_validation!
    return unless @estimate

    redirect_to root_path, warning: 'You cannot edit validated estimate' if @estimate.validated
  end
end

app/controllers/estimates_controller.rb
# frozen_string_literal: true

class EstimatesController < ApplicationController
  before_action :set_estimate, only: %i[show edit update destroy validate]
  before_action :check_validation!, only: %i[update destroy]

  def index
    @estimates = Estimate.all
  end

  def show; end

  def edit; end

  def new
    @estimate = Estimate.new
  end

  def destroy
    @estimate.destroy!

    redirect_to estimates_path, warning: "Estimate #{@estimate.label} deleted successfully"
  end

  def create
    @estimate = Estimate.create!(estimate_params)

    if @estimate.save
      redirect_to estimates_url, notice: 'Estimate was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @estimate.update(estimate_params)
      redirect_to edit_estimate_url(@estimate), notice: 'Estimate was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_estimate
    @estimate = Estimate.find(params[:id])
  end

  def estimate_params
    params.require(:estimate)
          .permit(
            :label,
            :date,
            :validated
          )
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :set_item, only: %i[edit update destroy]
  before_action :set_estimate, only: %i[new edit update destroy create]
  before_action :check_validation!, only: %i[create update destroy]

  def new
    @item = @estimate.items.new
  end

  def edit;end

  def create
    @item = @estimate.items.create!(item_params)

    if @item.save
      redirect_to estimate_url(@estimate), notice: 'Item was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @item.update(item_params)
      redirect_to estimate_items_url(@item, @estimate.id), notice: 'Item was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item.destroy

    redirect_to estimate_url(@estimate), notice: 'Item was deleted updated.'
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def set_estimate
    @estimate = Estimate.find(params[:estimate_id])
  end

  def item_params
    params.require(:item).permit(:name, :description, :unit_price, :quantity, :vat_rate)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render("#{association.to_s.singularize}_fields", f: builder)
    end
    link_to(name, '#', class: 'add_fields', data: { id:, fields: fields.gsub("\n", '') })
  end
end

app/views/estimates/_form.html.erb
<div class='container'>
<h2>Add a New Estimate</h1>
<%= semantic_form_for @estimate, html: { class: 'form-horizontal' } do |f| %>
  <%= f.inputs do %>
    <div class="form-group">
      <div class="col-sm-10">
        <%= f.input :label, label: 'Label', input_html: { class: 'form-control', placeholder: 'Label' } %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-10">
        <%= f.input :date, as: :date_picker, label: 'Date', input_html: { class: 'form-control', placeholder: 'Date' } %>
      </div>
    </div>

    <div class="form-check">
      <div class="col-sm-10">
        <%= f.input :validated, as: :radio, label: 'Validated', label_html: { class: 'radio-inline' } %>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col">
      <%= f.action :submit, as: :input, button_html: { class: 'btn btn-primary' } %>
    </div>
    <div class="col">
      <p><%= link_to 'Back to Estimates', estimates_path, class: 'btn btn-secondary' %></p>
    </div>
  </div>

<% end %>
</div>

app/views/estimates/edit.html.erb
<div class='container'>
<h1>Edit </h1>
 <%= semantic_form_for @estimate, html: { class: 'form-horizontal' } do |f| %>
  <%= f.inputs do %>
    <div class="form-group">
      <%= f.label :label, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.input :label, label: false, input_html: { class: 'form-control', placeholder: 'Label' } %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :date, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.input :date, as: :datetime_picker, label: false, input_html: { class: 'form-control', placeholder: 'Date' } %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :validated, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.input :validated, as: :radio, label: 'Validated', label_html: { class: 'radio-inline' } %>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.action :submit, as: :input, button_html: { class: 'btn btn-primary' } %>
    </div>
  </div>
<% end %>

<br>


<div class="row">
    <div class="col">
  <%= link_to "Show this estimate", @estimate, class: 'btn btn-secondary' %>
    </div>
    <div class="col">
  <%= link_to "Back to estimates", estimates_path, class: 'btn btn-secondary' %>
    </div>
  </div>

<div>
</div>

app/views/estimates/index.html.erb
<h1>Listing Estimates</h1>

<table style='margin: 30px' class='table' >
  <thead>
    <tr>
      <th scope='col' >Id</th>
      <th scope='col'>Name</th>
      <th scope='col'>Date</th>
      <th scope='col'>Total Amount</th>
      <th scope='col'>Validated</th>
      <th scope='col' colspan="4">Actions</th>
    </tr>
  </thead>

  <div class='col-md-6'>
    <%= link_to "New estimate", new_estimate_path, class: 'btn btn-primary' %>
  </div>

  <tbody>
    <% @estimates.each do |estimate| %>
      <tr>
        <td><%= estimate.id %></td>
        <td><%= estimate.label %></td>
        <td><%= estimate.date&.strftime("%B %d, %Y") %></td>
        <td><%= estimate.total_with_tax %> € </td>
        <td>
          <% if estimate.validated %>
            <p style='color: green'> Validated </p>
          <% else %>
            <p style='color: red'> Not Validated </p>
          <% end %>
        </td>
        <td>
        <div class="btn-group-sm">
         <button class='btn btn-outline-primary' >
          <%= link_to "View Estimate", estimate_path(estimate.id), method: :get %>
          </button>
          <button class='btn btn-warning' >
            <%= link_to_if !estimate.validated, "Edit Estimate" , edit_estimate_path(estimate.id), method: :get %>
          </button>
           <button class='btn btn-danger' >
            <%= link_to_if !estimate.validated, "Delete Estimate", estimate, method: :delete,
            data: { 'turbo-method': :delete }
            %>
          </button>
        </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/estimates/new.html.erb
<%= render "form" %>

app/views/estimates/show.html.erb
<div class='container'>
  <% if @estimate %>
    <h2>Estimate Information</h2>
    <table class='table' >
      <tr>
        <th>Estimate ID</th>
        <td><%= @estimate.id %></td>
      </tr>
      <tr>
        <th>Date of Estimate</th>
        <td><%= @estimate.date&.strftime("%B %d, %Y") %></td>
      </tr>
      <tr>
        <th>Validated</th>
        <td>
        <% if @estimate.validated %>
            <p style='color: green'> Validated </p>
          <% else %>
            <p style='color: red'> Not Validated </p>
          <% end %>
        </td>
      </tr>
    </table>
  <% else %>
    <p>Estimate not found.</p>
  <% end %>

  <% if @estimate.items.any? %>
    <h2>Items</h2>
    <table class='table'>
      <tr>
        <th>Item Id</th>
        <th>Item Name</th>
        <th>Description</th>
        <th>Quantity</th>
        <th>Unit Price</th>
        <th>Vat rate</th>
        <th>Total Price</th>
        <th colspan="3">Actions</th>
      </tr>
      <% @estimate.items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= item.name %></td>
          <td><%= item.description %></td>
          <td><%= item.quantity %></td>
          <td><%= item.unit_price %> € </td>
          <td><%= "#{item.vat_rate.to_s} %" %></td>
          <td><%= item.total_price_with_vat %></td>
          <td>
          <button class='btn btn-warning'>
            <%= link_to_if !@estimate.validated, "Edit", edit_estimate_item_path(@estimate, item) %></td>
          </button>

          <td>
          <button class='btn btn-danger'>
            <%= link_to_if !@estimate.validated, "Destroy", estimate_item_path(@estimate, item) ,
            method: :delete,
              data: { 'turbo-method': :delete }%>
          </button>
            </td>
        </tr>
      <% end %>
    </table>
  <% else %>
    <p>No items found for this estimate.</p>
  <% end %>

    <div class="row">
    <div class="col">
      <%= link_to_if !@estimate.validated, 'Add new Item', new_estimate_item_path(@estimate), class: 'btn btn-primary' %>
    </div>
    <div class="col">
    <p><%= link_to 'Back to Estimates', estimates_path, class: 'btn btn-secondary' %></p>
    </div>
  </div>

  <div class="container">
        <table class="table table-sm">
            <tbody>
                <tr>
                    <td>Total HT:</td>
                    <td><%= @estimate.total_base_amount %> €</td>
                </tr>
                <tr>
                    <td>Total TVA:</td>
                    <td><%= @estimate.total_vat_amount %> €</td>
                </tr>
                <tr>
                    <td>Total TTC:</td>
                    <td><%= @estimate.total_with_tax %> €</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

app/views/items/_form.html.erb
<%= semantic_form_for [@estimate, @item], html: { class: 'form-horizontal' } do |form| %>
  <%= form.inputs do %>
    <div class="form-group">
      <%= form.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= form.input :name, label: false, input_html: { class: 'form-control', placeholder: 'Name' } %>
        <%= form.semantic_errors :name %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :description, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= form.input :description, label: false, input_html: { class: 'form-control', placeholder: 'Description' } %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :quantity, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= form.input :quantity, label: false, input_html: { class: 'form-control', placeholder: 'Quantity' } %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :unit_price, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= form.input :unit_price, label: false, input_html: { class: 'form-control', placeholder: 'Unit Price' } %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :vat_rate, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= form.input :vat_rate, prompt: @item.vat_rate, as: :select, collection: Item::ALLOWED_VAT_RATES, label: false, input_html: { class: 'form-control' } %>
        <%= form.semantic_errors :vat_rate %>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col">
      <%= form.action :submit, as: :input, button_html: { class: 'btn btn-primary' } %>
    </div>
    <div class="col">
      <%= link_to "Back to Estimate", estimate_path(@estimate), class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class='container'>
  <h2>Editing item</h2>

  <%= render "form", item: @item %>
</div>

app/views/items/new.html.erb
<div class='container'>
  <h2>New item</h2>

  <%= render "form", item: @item %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<!--Bootstrap CDN  -->
  <head>
    <title>EstimateApp</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <div class='container-xl'>
    <%= yield %>
    <% if flash[:notice].present? %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <% if flash[:warning].present? %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= flash[:warning] %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
   </div>
  </body>
</html>